dist: trusty
sudo: required

language: python
python:
  - "3.6"

cache: 
    directories:
        - /home/travis/build/SudoSharma/bimpm_implementation/.vector_cache
        - /home/travis/.cache/pip

branches:
    only:
        - master
        - develop

install: source travis/install.sh
script: python train.py -t 
